/**
 * Maps a `next/image` request onto the WebP variants generated by
 * `scripts/optimize-images.mjs`. A static export ships without an image
 * optimiser, so the variants are built ahead of time and this only picks one.
 */
const WIDTHS = [256, 384, 640, 750, 828, 1080, 1254];

// Configuring a custom loader hands it EVERY image and stops Next from adding
// `basePath` to any of them — including the ones this loader passes straight
// through. Miss that and a subdirectory deploy 404s the logo. It already did.
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const withBasePath = (p: string) =>
  BASE_PATH && p.startsWith("/") && !p.startsWith(`${BASE_PATH}/`) ? `${BASE_PATH}${p}` : p;

export default function localLoader({ src, width }: { src: string; width: number }) {
  // Anything outside /programs/ (the SVG wordmark, say) is served as authored —
  // a vector resizes losslessly and has no variants to choose from.
  const match = /^\/programs\/([^/]+)\.(?:jpe?g|png)$/i.exec(src);
  if (!match) return withBasePath(src);

  // Snap up to the narrowest variant that still covers the request, so the
  // browser never scales an image up.
  const target = WIDTHS.find((w) => w >= width) ?? WIDTHS.at(-1)!;
  return withBasePath(`/programs/_opt/${match[1]}-${target}.webp`);
}
