/**
 * Maps a `next/image` request onto the WebP variants generated by
 * `scripts/optimize-images.mjs`. A static export ships without an image
 * optimiser, so the variants are built ahead of time and this only picks one.
 *
 * Anything outside `/programs/` (the SVG wordmark, for instance) is returned
 * untouched — vectors resize losslessly and have nothing to gain.
 */
const WIDTHS = [256, 384, 640, 750, 828, 1080, 1254];

// Next prefixes `basePath` onto its own image URLs but NOT onto a custom
// loader's, so a project-subdirectory deploy 404s every image unless we do it.
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export default function localLoader({ src, width }: { src: string; width: number }) {
  const match = /^\/programs\/([^/]+)\.(?:jpe?g|png)$/i.exec(src);
  if (!match) return src;

  // Snap up to the narrowest variant that still covers the request, so the
  // browser never scales an image up.
  const target = WIDTHS.find((w) => w >= width) ?? WIDTHS.at(-1)!;
  return `${BASE_PATH}/programs/_opt/${match[1]}-${target}.webp`;
}
